### ISSUE TITLE
The video is invalid

### ISSUE THREAD

**Issue by XuankeShi** [alleboudy/detectozord#3]
Hi , i am very interested at  your project,but the video link is invalid, i can't watch it directly and i can't understanding your work directly, 
Thanks

**Comment by alleboudy** [comment]
Hi, unfortunately, youtube is blocked in China. if you have a preference for a more global video sharing website please point it out so that I can re-upload the video there.
To understand the work done here, I highly recommend reading more about OpenCV, PCL and tensorflow before trying the project as basic knowledge of these tools might not be sufficient.

**Comment by XuankeShi** [comment]
but  i've use vpn，i can watch the video on the youtube,i think may be you can put the video on the github,In this case, more people can pay attention to your work.
